<svg
  xmlns="http://www.w3.org/2000/svg"
  xmlns:xlink="http://www.w3.org/1999/xlink"
  viewBox="0 0 24 19"
  width="24"
  height="19"
  version="1.1"
  {...$$restProps}
>
  <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
    <g>
      <rect fill-rule="nonzero" x="0" y="0" width="24" height="24" />
      <line
        x1="5"
        y1="7"
        x2="19"
        y2="7"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
      />
      <line
        x1="5"
        y1="12"
        x2="19"
        y2="12"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
      />
      <line
        x1="5"
        y1="17"
        x2="19"
        y2="17"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
      />
    </g>
  </g>
</svg>
